# Generated by Django 3.2 on 2024-03-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.CharField(max_length=100)),
                ('clasevehiculo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
                ('placa', models.CharField(max_length=100)),
                ('ven_soat', models.DateField(default=django.utils.timezone.now)),
                ('ven_tecno', models.DateField(default=django.utils.timezone.now)),
                ('frontal', models.ImageField(blank=True, upload_to='media/ambulancia')),
                ('lateral', models.ImageField(blank=True, upload_to='media/ambulancia')),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('kilometraje', models.IntegerField()),
                ('remicion', models.IntegerField()),
                ('firma', models.ImageField(blank=True, upload_to='media/firma')),
                ('foto', models.ImageField(blank=True, upload_to='media/kilometraje')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flota.ambulancia')),
            ],
        ),
    ]
