# Generated by Django 3.2 on 2024-05-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_auto_20240429_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancia',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
