# Generated by Django 3.2 on 2024-05-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_alter_ambulancia_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
