# Generated by Django 3.2 on 2024-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_registros_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancia',
            name='frontal',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='lateral',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
